# Type stubs for the native `nopaldb.nopaldb` extension module (PyO3).
# Kept in sync with src/python/*.rs. See python/scripts/check_stubs.py.
from typing import Any, Iterator, Optional

__version__: str
__author__: str

# Property values accepted/returned across the API.
Property = str | int | float | bool | bytes | None
Props = dict[str, Property]

class Graph:
    # ── Construction ────────────────────────────────────────────────
    @staticmethod
    def open(path: str) -> "Graph": ...
    @staticmethod
    def open_with_profile(path: str, profile: str = "default") -> "Graph": ...
    @staticmethod
    def open_with_options(path: str, engine: str = "sled", profile: str = "default") -> "Graph": ...
    @staticmethod
    def in_memory() -> "Graph": ...
    @staticmethod
    def in_memory_with_profile(profile: str = "default") -> "Graph": ...
    @staticmethod
    def in_memory_with_options(engine: str = "sled", profile: str = "default") -> "Graph": ...

    # ── Queries & transactions ──────────────────────────────────────
    def execute_nql(self, query: str) -> "NqlResult": ...
    def begin_transaction(self, isolation: Optional[str] = None) -> "Transaction": ...

    # ── Idempotent upsert (M1-4) ────────────────────────────────────
    def upsert(
        self,
        label: str,
        key: str,
        props: Props,
        vector: Optional[list[float]] = None,
        model: Optional[str] = None,
        links: Optional[list[dict[str, Any]]] = None,
    ) -> tuple[str, str]: ...
    def upsert_many(self, requests: list[dict[str, Any]]) -> list[tuple[str, str]]: ...

    # ── Schema & stats ──────────────────────────────────────────────
    def node_count(self) -> int: ...
    def get_labels(self) -> list[str]: ...
    def get_edge_types(self) -> list[str]: ...
    def get_schema(self) -> dict[str, Any]: ...
    def get_label_properties(self, label: str) -> list[str]: ...
    def get_label_count(self, label: str) -> int: ...
    def get_edge_type_properties(self, edge_type: str) -> list[str]: ...
    def get_edge_type_count(self, edge_type: str) -> int: ...
    def rebuild_schema(self) -> None: ...
    def get_stats(self) -> dict[str, str]: ...

    # ── Indexes ─────────────────────────────────────────────────────
    def create_index(self, label: str, property: str, index_type: str = "hash") -> None: ...
    def drop_index(self, index_name: str) -> None: ...
    def list_indexes(self) -> list[tuple[str, str, str, str]]: ...

    # ── Arrow export ────────────────────────────────────────────────
    def to_arrow(self) -> Any: ...
    def edges_to_arrow(self) -> Any: ...
    def to_arrow_complete(self) -> Any: ...
    def bulk_loader(self) -> "BulkLoader": ...

    # ── Embeddings & vector search ──────────────────────────────────
    def add_node_embedding(self, node_id: str, vector: list[float], model: str) -> None: ...
    def add_edge_embedding(self, edge_id: str, vector: list[float], model: str) -> None: ...
    def add_path_reference_embedding(
        self, name: str, node_model: str, edge_model: str, vector: list[float]
    ) -> None: ...
    def get_node_embedding(self, node_id: str, model: str) -> list[float]: ...
    def knn_nodes(self, query_vector: list[float], k: int, model: str) -> list[tuple[str, float]]: ...

    # ── Semantic layer ──────────────────────────────────────────────
    def import_turtle(self, ttl_source: str) -> dict[str, Any]: ...

    # ── Lifecycle ───────────────────────────────────────────────────
    def close(self) -> None: ...
    def __enter__(self) -> "Graph": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...

class Transaction:
    def add_node(self, label: str, properties: Props) -> str: ...
    def add_edge(
        self, source: str, target: str, edge_type: str, properties: Optional[Props] = None
    ) -> str: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __repr__(self) -> str: ...

class QueryResult:
    @property
    def columns(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
    def __getitem__(self, index: int) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class ProfileResult:
    @property
    def plan(self) -> str: ...
    @property
    def statement_type(self) -> str: ...
    @property
    def execution_ms(self) -> float: ...
    @property
    def rows_returned(self) -> int: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def path_query(self) -> bool: ...
    @property
    def path_metrics(self) -> Optional[Any]: ...
    def __repr__(self) -> str: ...

class NqlResult:
    @property
    def kind(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def query(self) -> Optional[QueryResult]: ...
    @property
    def write(self) -> Optional[Any]: ...
    @property
    def explain(self) -> Optional[str]: ...
    @property
    def profile(self) -> Optional[ProfileResult]: ...
    @property
    def message(self) -> Optional[str]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
    def __getitem__(self, index: int) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class BulkLoader:
    def add_node(self, label: str, properties: Props) -> str: ...
    def add_edge(
        self, source: str, target: str, edge_type: str, properties: Optional[Props] = None
    ) -> str: ...
    def finish(self) -> Any: ...
    def __enter__(self) -> "BulkLoader": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def __repr__(self) -> str: ...

# ── Semantic reasoner (feature `python-reasoner`) ───────────────────
class Inference:
    @property
    def sub(self) -> str: ...
    @property
    def super_class(self) -> str: ...
    @property
    def rule(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

class ELReasoner:
    def __init__(self) -> None: ...
    def register_class(self, node_id: str, label: str) -> None: ...
    def assert_subclass(self, sub: str, super_class: str) -> list[Inference]: ...
    def assert_conjunction(self, sub: str, conj1: str, conj2: str) -> list[Inference]: ...
    def assert_existential(self, sub: str, role: str, filler: str) -> list[Inference]: ...
    def assert_existential_domain(self, role: str, filler: str, super_class: str) -> list[Inference]: ...
    def classify_all(self) -> list[Inference]: ...
    def is_subclass_of(self, sub: str, super_class: str) -> bool: ...
    def superclasses(self, node: str) -> list[str]: ...
    def subclasses(self, node: str) -> list[str]: ...
    def axiom_count(self) -> int: ...
    def derived_count(self) -> int: ...
    def derived_inferences(self) -> list[Inference]: ...
    def __repr__(self) -> str: ...
