#!/usr/bin/env python3
"""
QA Challenge checks for NopalDB Python wrapper.
Uses the same persistent DB generated by qa_challenge_suite.rs.
"""

import argparse
import sys

import nopaldb


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--db",
        default="./nopaldb/test_dbs/qa_challenge_db",
        help="Path to persistent QA challenge DB",
    )
    return p.parse_args()


def assert_true(cond: bool, msg: str) -> None:
    if not cond:
        raise AssertionError(msg)


def main() -> int:
    args = parse_args()

    print("\n=== QA Challenge Checks (Python) ===")
    print(f"DB: {args.db}")

    graph = nopaldb.Graph.open(args.db)

    labels = set(graph.get_labels())
    edge_types = set(graph.get_edge_types())
    schema = graph.get_schema()
    stats = graph.get_stats()

    print(f"Labels: {sorted(labels)}")
    print(f"Edge types: {sorted(edge_types)}")
    print(f"Stats: {stats}")

    assert_true("User" in labels, "User label missing")
    assert_true("Project" in labels, "Project label missing")
    assert_true("MEMBER_OF" in edge_types, "MEMBER_OF edge type missing")
    assert_true(int(stats["total_nodes"]) > 0, "total_nodes should be > 0")

    idx_before = graph.list_indexes()
    print(f"Indexes: {idx_before}")
    assert_true(len(idx_before) >= 3, "Expected >=3 indexes")

    # Query: aggregation
    team_counts = graph.execute_nql(
        "find u.team, count(u) as total from (u:User) group by u.team order by u.team asc"
    )
    print(f"Team aggregation rows: {len(team_counts)}")
    assert_true(len(team_counts) >= 4, "Expected at least 4 teams")

    # Query: pattern matching
    membership = graph.execute_nql(
        "find u.username, p.name from (u:User) -> [:MEMBER_OF] -> (p:Project) limit 20"
    )
    print(f"Pattern rows: {len(membership)}")
    assert_true(len(membership) > 0, "Pattern query returned no rows")

    # Query: algorithm functions
    algo = graph.execute_nql(
        "find degree(u) as deg, pagerank(u) as pr from (u:User) limit 5"
    )
    print(f"Algorithm rows: {len(algo)}")
    assert_true(len(algo) > 0, "Algorithm query returned no rows")

    # Write statement via execute_nql compatibility
    graph.execute_nql(
        'update (u:User) set u.qa_checked = "yes" where u.username = "user_001" limit 1'
    )

    post_update = graph.execute_nql(
        'find u.username from (u:User) where u.qa_checked = "yes" limit 10'
    )
    print(f"Rows with qa_checked=yes: {len(post_update)}")
    assert_true(len(post_update) > 0, "UPDATE check failed")

    # Transaction rollback test
    tx = graph.begin_transaction()
    tx.add_node("TransientPy", {"name": "py_rollback_marker"})
    tx.rollback()

    rollback_check = graph.execute_nql(
        'find t.name from (t:TransientPy) where t.name = "py_rollback_marker"'
    )
    assert_true(len(rollback_check) == 0, "Python rollback check failed")

    # Index API from Python
    graph.create_index("User", "qa_checked", "hash")
    idx_after = graph.list_indexes()
    assert_true(any(name == "User_qa_checked" for name, *_ in idx_after), "Python index create failed")

    # Optional Arrow checks
    try:
        node_arrow = graph.to_arrow("User")
        edge_arrow = graph.edges_to_arrow()
        print(f"Arrow bytes: nodes={len(node_arrow)}, edges={len(edge_arrow)}")
        assert_true(len(node_arrow) > 0, "Arrow nodes bytes empty")
    except Exception as exc:
        print(f"Arrow not available in this build: {exc}")

    graph.close()

    print("✅ Python checks completed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"❌ QA Python checks failed: {exc}")
        raise
